In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

In [2]:
from src.data.download import (
    download_stock_data,
    save_raw_data,
)

In [3]:
df = download_stock_data(
    ticker="TSLA",
    start_date="2020-06-29",
    end_date="2026-04-24"
)

[*********************100%***********************]  1 of 1 completed

In [5]:
df.columns = df.columns.get_level_values(0)  
df.head()

Price           Close       High        Low       Open     Volume
Date
2020-06-29  67.290001  67.333336  63.234669  64.600670  135396000
2020-06-30  71.987335  72.512665  66.915337  67.099998  253777500
2020-07-01  74.641998  75.688667  72.033333  72.199997  199903500
2020-07-02  80.577332  81.866669  79.040001  81.431999  258751500
2020-07-06  91.438667  91.852669  84.402664  85.112663  308548500

In [6]:
df.isnull().sum()

Price
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [7]:
df.duplicated().value_counts()

False    1462
Name: count, dtype: int64

In [8]:
df.describe()

Price        Close         High          Low         Open        Volume
count  1462.000000  1462.000000  1462.000000  1462.000000  1.462000e+03
mean    261.933136   267.703221   255.962947   262.032409  1.056626e+08
std      87.232919    88.907077    85.706068    87.474325  5.408552e+07
min      67.290001    67.333336    63.234669    64.600670  2.940180e+07
25%     200.844997   204.704163   195.342495   200.515003  7.017875e+07
50%     245.476669   251.253334   240.699997   245.105003  9.376550e+07
75%     319.334999   326.250000   311.589996   319.662491  1.232412e+08
max     489.880005   498.829987   485.329987   489.880005  6.663786e+08

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1462 entries, 2020-06-29 to 2026-04-23
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Close   1462 non-null   float64
 1   High    1462 non-null   float64
 2   Low     1462 non-null   float64
 3   Open    1462 non-null   float64
 4   Volume  1462 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 68.5 KB

In [4]:
save_raw_data(df, 'raw.csv')

Saved to /Users/pj/Desktop/StockMarket Analyze/data/raw/raw.csv