In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

In [2]:
from src.features.indicators import *
from src.config import RAW_DATA, PROCESSED_DATA, VISUALIZATION_DATA

import pandas as pd

In [3]:
df = pd.read_csv(
    RAW_DATA / "raw.csv",
    index_col="Date",
    parse_dates=True
)

df.head()

                Close       High        Low       Open     Volume
Date
2020-06-29  67.290001  67.333336  63.234669  64.600670  135396000
2020-06-30  71.987335  72.512665  66.915337  67.099998  253777500
2020-07-01  74.641998  75.688667  72.033333  72.199997  199903500
2020-07-02  80.577332  81.866669  79.040001  81.431999  258751500
2020-07-06  91.438667  91.852669  84.402664  85.112663  308548500

In [ ]:
df = create_technical_indicators(df)

,Close,High,Low,Open,Volume,rsi,RSI_Signal,EMA26,EMA12,macd,...,%D,SO_signal,SO_Position,MA10,MA50,Signal,Daily_Return,Position,days_from_month_start,days_to_month_end
Date,,,,,,,,,,,,,,,,,,,,,
2020-06-29,67.290001,67.333336,63.234669,64.600670,135396000,NaN,0.0,67.290001,67.290001,0.000000,...,NaN,0,0.0,NaN,NaN,0,NaN,0.0,28,1
2020-06-30,71.987335,72.512665,66.915337,67.099998,253777500,NaN,0.0,67.637952,68.012668,0.374716,...,NaN,0,0.0,NaN,NaN,0,0.069807,0.0,29,0
2020-07-01,74.641998,75.688667,72.033333,72.199997,199903500,NaN,0.0,68.156770,69.032565,0.875795,...,NaN,0,0.0,NaN,NaN,0,0.036877,0.0,0,30
2020-07-02,80.577332,81.866669,79.040001,81.431999,258751500,NaN,0.0,69.076811,70.808683,1.731871,...,NaN,0,0.0,NaN,NaN,0,0.079517,0.0,1,29
2020-07-06,91.438667,91.852669,84.402664,85.112663,308548500,NaN,0.0,70.733245,73.982526,3.249281,...,NaN,0,0.0,NaN,NaN,0,0.134794,0.0,5,25

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1462 entries, 2020-06-29 to 2026-04-23
Data columns (total 47 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Close            1462 non-null   float64
 1   High             1462 non-null   float64
 2   Low              1462 non-null   float64
 3   Open             1462 non-null   float64
 4   Volume           1462 non-null   int64
 5   rsi              1449 non-null   float64
 6   RSI_Signal       1462 non-null   float64
 7   EMA26            1462 non-null   float64
 8   EMA12            1462 non-null   float64
 9   macd             1462 non-null   float64
 10  Signal_line      1462 non-null   float64
 11  macd_signal      1462 non-null   int64
 12  macd_position    1462 non-null   float64
 13  middle_band      1443 non-null   float64
 14  upper_band       1443 non-null   float64
 15  lower_band       1443 non-null   float64
 16  above_bb_high    1462 non-null   int64
 17  below_bb_low     1462 non-null   int64
 18  TR               1462 non-null   float64
 19  +DM              1462 non-null   float64
 20  -DM              1462 non-null   float64
 21  Smoothed +DM     1449 non-null   float64
 22  Smoothed -DM     1449 non-null   float64
 23  Smoothed TR      1449 non-null   float64
 24  +DI              1449 non-null   float64
 25  -DI              1449 non-null   float64
 26  DX               1449 non-null   float64
 27  ADX              1436 non-null   float64
 28  adx_Signal       1462 non-null   int64
 29  adx_Position     1462 non-null   float64
 30  OBV              1462 non-null   float64
 31  PVT              1461 non-null   float64
 32  Signal Line_PVT  1453 non-null   float64
 33  pvt_signal       1462 non-null   int64
 34  pvt_Position     1462 non-null   float64
 35  VROC             1432 non-null   float64
 36  rolling_min      1449 non-null   float64
 37  rolling_max      1449 non-null   float64
 38  %K               1449 non-null   float64
 39  %D               1447 non-null   float64
 40  SO_signal        1462 non-null   int64
 41  SO_Position      1462 non-null   float64
 42  MA10             1453 non-null   float64
 43  MA50             1413 non-null   float64
 44  Signal           1462 non-null   int64
 45  Daily_Return     1461 non-null   float64
 46  Position         1462 non-null   float64
dtypes: float64(39), int64(8)
memory usage: 548.2 KB

In [12]:
df.describe()

,Close,High,Low,Open,Volume,rsi,RSI_Signal,EMA26,EMA12,macd,...,rolling_max,%K,%D,SO_signal,SO_Position,MA10,MA50,Signal,Daily_Return,Position
count,1462.000000,1462.000000,1462.000000,1462.000000,1.462000e+03,1449.000000,1462.000000,1462.000000,1462.000000,1462.000000,...,1449.000000,1449.000000,1447.000000,1462.000000,1462.0000,1453.000000,1413.000000,1462.000000,1461.000000,1462.000000
mean,261.933136,267.703221,255.962947,262.032409,1.056626e+08,51.873811,0.471272,259.272847,260.763075,1.490228,...,284.070024,52.870649,52.836252,0.452120,0.0000,262.116052,262.736525,0.526676,0.001929,0.000000
std,87.232919,88.907077,85.706068,87.474325,5.408552e+07,17.987884,0.499345,84.592938,86.045570,11.396148,...,90.316511,36.679086,34.178031,0.497873,0.6057,85.713227,79.319826,0.499459,0.038984,0.156973
min,67.290001,67.333336,63.234669,64.600670,2.940180e+07,6.919326,0.000000,67.290001,67.290001,-35.583228,...,102.639999,0.000000,0.000000,0.000000,-1.0000,86.538401,109.877707,0.000000,-0.210628,-1.000000
25%,200.844997,204.704163,195.342495,200.515003,7.017875e+07,39.605994,0.000000,202.727498,201.258261,-6.599998,...,218.856674,17.220737,19.728091,0.000000,0.0000,201.863000,209.896935,0.000000,-0.020151,0.000000
50%,245.476669,251.253334,240.699997,245.105003,9.376550e+07,50.968524,0.000000,243.622931,244.933166,1.519651,...,263.260010,54.219869,56.176691,0.000000,0.0000,245.945999,247.591467,1.000000,0.001463,0.000000
75%,319.334999,326.250000,311.589996,319.662491,1.232412e+08,63.759760,1.000000,317.852735,318.407699,7.142050,...,348.679993,89.427825,85.369376,1.000000,0.0000,319.124997,312.926667,1.000000,0.022218,0.000000
max,489.880005,498.829987,485.329987,489.880005,6.663786e+08,97.529933,1.000000,458.887848,473.017178,40.538606,...,489.880005,100.000000,100.000000,1.000000,1.0000,479.154004,445.266002,1.000000,0.226900,1.000000

In [14]:
df.isna().sum()

Close               0
High                0
Low                 0
Open                0
Volume              0
rsi                13
RSI_Signal          0
EMA26               0
EMA12               0
macd                0
Signal_line         0
macd_signal         0
macd_position       0
middle_band        19
upper_band         19
lower_band         19
above_bb_high       0
below_bb_low        0
TR                  0
+DM                 0
-DM                 0
Smoothed +DM       13
Smoothed -DM       13
Smoothed TR        13
+DI                13
-DI                13
DX                 13
ADX                26
adx_Signal          0
adx_Position        0
OBV                 0
PVT                 1
Signal Line_PVT     9
pvt_signal          0
pvt_Position        0
VROC               30
rolling_min        13
rolling_max        13
%K                 13
%D                 15
SO_signal           0
SO_Position         0
MA10                9
MA50               49
Signal              0
Daily_Return        1
Position            0
dtype: int64

In [ ]:
df.to_csv(VISUALIZATION_DATA / "tesla_features.csv")